import { test } from 'node:test';
import assert from 'node:assert/strict';
const { watchTOTPCycle } = await import('../src/utils/totp-cycle.ts');

test('cycle refresh runs once, catches skipped cycles and resumes; cleanup stops work', (t) => {
  let now = 29_900;
  let callback;
  let cleared = false;
  let refreshes = 0;
  const target = new EventTarget();
  target.visibilityState = 'visible';
  Object.defineProperty(globalThis, 'document', { configurable: true, value: target });
  t.after(() => { delete globalThis.document; });
  t.mock.method(Date, 'now', () => now);
  t.mock.method(globalThis, 'setInterval', (fn) => { callback = fn; return 123; });
  t.mock.method(globalThis, 'clearInterval', (id) => { assert.equal(id, 123); cleared = true; });
  const stop = watchTOTPCycle(() => { refreshes++; });
  assert.equal(refreshes, 1);
  now = 30_000;
  for (let i = 0; i < 100; i++) callback();
  assert.equal(refreshes, 2);
  now = 91_000;
  callback();
  assert.equal(refreshes, 3);
  target.visibilityState = 'hidden';
  now = 150_000;
  callback();
  target.dispatchEvent(new Event('visibilitychange'));
  assert.equal(refreshes, 3);
  target.visibilityState = 'visible';
  target.dispatchEvent(new Event('visibilitychange'));
  callback();
  assert.equal(refreshes, 4);
  now = 10_000;
  callback();
  assert.equal(refreshes, 5);
  stop();
  assert.equal(cleared, true);
  target.dispatchEvent(new Event('visibilitychange'));
  assert.equal(refreshes, 5);
});
